# -*- coding: utf-8 -*-
"""dog

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3ffWLzyr2kXkcqK5lGid4pwGBsshK7L
"""

class Dogworld:
  """We're attempting to model a dog. This will help
  the user understand how to use OOP"""

  def __init__(self, name, age):
        self.name = name
        self.age = age
        self.Tail = "long"

  def dogname(self):
    return f"Hello {self.name}."

  def dogage(self):
    return f"your age is {self.age}."

  def dogtail(self):
    return f"Their dog tail is {self.Tail}."

  def UpdateDog(self, name, age, tail):
    self.Tail = tail
    return f"This is {self.name}, he is {self.age} years old and has a {self.Tail} tail."