# -*- coding: utf-8 -*-
"""Practicing_List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyGti_fNVaHqzK4en3VGJ3qilH-pUR_B
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dog.py
# 
# 
# class Dogworld:
#   """We're attempting to model a dog. This will help
#   the user understand how to use OOP"""
# 
#   def __init__(self, name, age):
#         self.name = name
#         self.age = age
#         self.Tail = "long"
# 
#   def dogname(self):
#     return f"Hello {self.name}."
# 
#   def dogage(self):
#     return f"your age is {self.age}."
# 
#   def dogtail(self):
#     return f"Their dog tail is {self.Tail}."
# 
#   def UpdateDog(self, name, age, tail):
#     self.Tail = tail
#     return f"This is {self.name}, he is {self.age} years old and has a {self.Tail} tail."

# Commented out IPython magic to ensure Python compatibility.
# %%writefile SuperPowerDogs.py
# from dog import Dogworld
# 
# 
# class SuperPowerForDogs:
#   """This class is made for dogs that have powers"""
# 
#   def __init__(self, Color="Red and Green"):
#     self.Color = Color
# 
#   def Diff_Eyes(self):
#     return f"This dog has {self.Color} eyes."
# 
#   def get_Jump(self):
#     JumpHeight = 20
#     return f"This dog can jump {JumpHeight}ft in the air."
# 
#   def get_Speed(self):
#     Speed = 900
#     return f"That dog can run {Speed}mph."
# 
# 
# class SuperCorgi(Dogworld):
#   """This class is made for Super Corgis"""
# 
#   def __init__(self, name, age):
#     super().__init__(name, age)
#     self.DogPower = SuperPowerForDogs()
# 
#   def dogage(self):
#     return f"This Super Corgi is immortal."
#

import os
import random as ra
from pathlib import Path

from dog import Dogworld
from SuperPowerDogs import SuperCorgi
import json

#Practicing JSON
def store_name(name, path):
  print("We're going to store your name to remember you.")
  juser = json.dumps(name)
  path.write_text(juser)
  return name

def get_name(name, path):
  if path.exists():
    print("We have your name on file.")
    juser = path.read_text()
    get_user = json.loads(juser)
    return get_user
  else:
    return get_name(store_name(name, path), path)

def greeting():
  username = input("Hello, please write your name: ")
  path = Path (username + ".json")
  user = get_name(username, path)
  print (f"Welcome {user}!")

greeting()

#Practicing Exception
Trypath = Path('yics.txt')
try:
  Contents = Trypath.read_text()
except FileNotFoundError:
  print(f"!!!!!!!EITHER WRONG DIRECTORY OR WRONG FILE!!!!!!!.\nDouble check the directory and file name.\n---------End Of Message---------")
else:
  print(f"The file being tried is '{Trypath}'.")


#Practicing handling files
lyricsPath = Path('Lyrics.txt')
FileString = lyricsPath.read_text().rstrip()
print(f"{FileString}\n\n_____________THE END_____________")

#Practicing importing a module from the Python's standard library
randomNum = ra.randint(0,1)
Stadium_Food = ["Hotdog", "Philly Sub"]
print(randomNum)
Stadium_Food[randomNum] = "Pretzels"
Customer_Choice = ra.choice(Stadium_Food)
print(f"One of the customer's choice was: #{randomNum}. {Customer_Choice}")


#Practicing Classes
my_dog = Dogworld("Jake", 26)
print (f"{my_dog.dogname()}, you're my favorite dog and {my_dog.dogage()}")
print (f"My dog has a tail. {my_dog.dogtail()}")
my_dog.Tail = "Short"
print (f"My friend's dog has a tail. {my_dog.dogtail()}")
Update = my_dog.UpdateDog("Kent", 49, "Medium")
print(Update)
print(f"Some people wish every dog tail is {my_dog.Tail}")
 ##Praticing Super Class
my_Corgi = SuperCorgi("Jamester", 20)
print(f"{my_Corgi.dogname()} {my_Corgi.dogtail()} {my_Corgi.DogPower.get_Speed()} {my_Corgi.dogage()}")


#Practicing strings
TempV = "Hi to them all"
Tempv2 = " hi "
SayHi = f"{TempV} {Tempv2}"
Greetings = f"Yes, Lets say {TempV} {Tempv2.strip()}!"
Tempv2 = Tempv2.strip()
print(Greetings.removeprefix('Yes,'),f"\n\t Jimmy said {Tempv2.title()}")


#Practicing Numbers
Num1, Num2, Num3, Num4 = 300,200,40000,5_00
expo = Num2 ** 2
Question = f"What is {Num1} + {Num2}? \n\t Jimmy said {Num4}\nWhat is {Num2} to the 2nd power?\n\t Jimmy said {expo}"
print(Question)


#Practicing Lists
csvfiles = []
file1 = "Sheet_1.csv"
file2 = "Sheet_2.csv"
file3 = "Sheet_3.csv"
csvfiles.append(file1)
csvfiles.append(file2)
csvfiles.insert(0, file3)
print(f"this is my list {csvfiles}")
csvfiles.sort()
print(f"this is my new list {csvfiles}")
csvfiles.reverse()
print(f"this is my new reverse list {csvfiles}")
popped_csvfiles = csvfiles.pop(0)
csvfiles.remove("Sheet_1.csv")
print(f"{popped_csvfiles} and {file1} was removed the list, but only {popped_csvfiles} will be put back")
csvfiles.append(popped_csvfiles)
print(f"this is my new list unsorted {csvfiles}\n\tThis list will be reversed:")
csvfiles.reverse()
print(f"\t{csvfiles}\n\t\tand reversed again:")
csvfiles.reverse()
print(f"\t\t{csvfiles}\nWe're now going to modify the last file:")
csvfiles[-1] = "Sheet_4.csv"
print(csvfiles)


#Practicing Lists Some More
dimensions = (200,50)
print(dimensions[0])
print(dimensions[1])
csvfiles.append("Sheet_3.csv")
csvfiles.append("Sheet_1.csv")
if "Sheet_4.csv" in csvfiles:
  print("Sheet 4 is here")
elif "Sheet_2.csv" in csvfiles:
  print("Sheet 2 is here")
if "Sheet_1.csv" in csvfiles:
  print("Sheet 1 is here")
if "Sheet_3.csv":
  print("Sheet 3 is here")
else:
  print(f"these are all the sheets that are available {csvfiles}")

snd_list = csvfiles[:]
snd_list.append("Sheet_6.csv")
snd_list.append("Sheet_9.csv")
csvfiles.pop(2)

for x in snd_list:
  if x in csvfiles:
    print(f"{x} is a match with the second list")
  else:
    print(f"No match for {x}")

print("finished matching experiment")
print(csvfiles)
print(snd_list)

#Practicing Dictionaries & List
business_ComicCorp = {}
business_RealEstateCorp = {}
Topics = ["Workplace_cultures", "Finances", "Innovations", "Trend_analysis"]
Workers = ["James", "Dominic", "Becky"]

Businesses = {'business_ComicCorp': business_ComicCorp, 'business_RealEstateCorp': business_RealEstateCorp}
start = 0
for business_Name, business in Businesses.items():
  for worker in Workers:
    business[worker] = Topics[start:]
    start += 1
    if business_Name == 'business_RealEstateCorp' and worker == 'James':
      business['Sally'] = business.pop('James')
    if business_Name == 'business_RealEstateCorp' and worker == 'Dominic':
      business['Falisha'] = business.pop('Dominic')
  for Key_Workers, Value_Topics in business.items():
    for Value in Value_Topics:
      print(f"For business {business_Name}, worker {Key_Workers.title()} is responsible for {Value.title()}")
  print(f"{business_Name}")
  start = 0
  if 'Becky' in business_RealEstateCorp:
    del Businesses['business_RealEstateCorp']["Becky"]
    print("\nBecky works at two different companies doing the samething and decided to start her own business.\nThis is the update for both companies \n", business)

#Practicing Inputs & While loops
Greeting = input("you asked ")
Greeting += " ...mm Good question"
print(Greeting)

while Greeting:
  print("Hello")
  if Greeting:
    print("NOO!")
    break

#Practicing Functions
def Fileiteration(filetype, file='business_RealEstate'):
  print(f"The file you're iterating is {file.title()}\nIt is a {filetype} file type")

while(start ==  0):
  inputfiletype = input("What type of file do you want to iterate? ").lower()
  inputfile = input("What is the name of the file, if nothing press enter: ")
  if (inputfiletype == 'excel' or inputfiletype == 'csv') and inputfile:
    Fileiteration(inputfiletype, inputfile)
  elif (inputfiletype == 'excel' or inputfiletype == 'csv') and not inputfile:
    Fileiteration(inputfiletype)
  else:
    print("File type was not a csv or excel")
    start = 1

def Generating_File_Message(Welcome, Update_Welcome):
  print("This is a list of the messages we're going to update", Welcome)
  while Welcome:
    Update = Welcome.pop()
    Update += ", Let's Continue"
    Update_Welcome.append(Update)

def Add_another_greet(Welcome):
  greet = input("Add another greetings: ")
  print(f"This is the original: {Welcome}")
  Welcome.append(greet)
  print(f"This is the copy that added the new greetings: {Welcome}")

def Print_File_Message(Welcome, Update_Welcome):
  print("The original shows that all of its items were moved to the updated list: ", Welcome)
  for update_welcome in Update_Welcome:
    print(Update_Welcome.index(update_welcome), ". From the the Updated list this is one of the updated messages: ", update_welcome)

Welcomings = ["Welcome_all", "Hi_User", "Welcome", "Hi"]
Updated_Welcomings = []

Generating_File_Message(Welcomings, Updated_Welcomings)
Add_another_greet(Welcomings[:])
Print_File_Message(Welcomings, Updated_Welcomings)

