# -*- coding: utf-8 -*-
"""SuperPowerDogs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApEZH2f9PW9G6xCa8KcVkBnVFpgV-bqo
"""

from dog import Dogworld


class SuperPowerForDogs:
  """This class is made for dogs that have powers"""

  def __init__(self, Color="Red and Green"):
    self.Color = Color

  def Diff_Eyes(self):
    return f"This dog has {self.Color} eyes."

  def get_Jump(self):
    JumpHeight = 20
    return f"This dog can jump {JumpHeight}ft in the air."

  def get_Speed(self):
    Speed = 900
    return f"That dog can run {Speed}mph."


class SuperCorgi(Dogworld):
  """This class is made for Super Corgis"""

  def __init__(self, name, age):
    super().__init__(name, age)
    self.DogPower = SuperPowerForDogs()

  def dogage(self):
    return f"This Super Corgi is immortal."